name: '8.0 Build & Push'
on:
  push:
    branches: master
    paths:
      - 8.0/**

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: lloydituk/php8.0-fpm:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}